services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-container
    environment:
      - ORACLE_PWD=1234
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=Europe/Madrid
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local

# docker-compose -f oracle-compose.yml up -d
# docker-compose -f oracle-compose.yml down
# docker-compose -f oracle-compose.yml down -v